### ISSUE TITLE
Obey "Draw Relationship Lines" setting

### ISSUE THREAD

**Issue by YeldhamDev** [Zylann/godot_editor_debugger_plugin#1]
Could make the tree obey the "Draw Relationship Lines" setting? It also hides the lines drawn in-between the items.

**Comment by Zylann** [comment]
I'm trying to do this:
```gdscript
	EditorSettings.connect("settings_changed", self, "_on_EditorSettings_settings_changed")
```
But Godot throws an error:
```
ERROR: In Object of type 'GDScriptNativeClass': Attempt to connect nonexistent signal 'settings_changed' to method 'EditorPlugin._on_EditorSettings_settings_changed'
   At: core/object.cpp:1404
```

In fact, `EditorSettings.get_setting` also doesn't work, not sure how I am supposed to access this singleton...
I'll try with `EditorInterface`, it's weird that singletons in C++ don't map those you have in GDScript

**Comment by Zylann** [comment]
231a74c328ee2d6ab3746acb3a5cc66894977ac4
I managed to make it work with the same code as the scene tree, but it still doesn't hide the lines between the items for some reason.
It also doesn't in the normal scene tree ¯\\_(ツ)_/¯  (in 3.0.6)

**Comment by YeldhamDev** [comment]
The new changes work completely fine in 3.1, so I'm closing the issue.

Thanks!
